name: Build Arch Package

on:
  push:
    branches: [ main, master ] # يعمل على كلا الاسمين لضمان التشغيل
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build PKGBUILD
        uses: arch-actions/run-makepkg@v1
        with:
          # إذا كان الملف في المجلد الرئيسي اتركه كما هو
          # إذا كان في مجلد فرعي اكتب اسمه هنا
          path: . 

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: ./*.pkg.tar.zst
